# Generated by Django 4.2.2 on 2023-06-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0002_alter_tasksmodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksmodel',
            old_name='id',
            new_name='uuid',
        ),
    ]
