# Generated by Django 4.2.2 on 2023-06-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0003_rename_id_tasksmodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='execution_status',
            field=models.BooleanField(choices=[(False, 'Pending'), (True, 'Completed')], default=False),
        ),
    ]
