# Generated by Django 4.2.2 on 2023-07-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0005_alter_usermodel_email_alter_usermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='execution_status',
            field=models.BooleanField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default=False),
        ),
    ]
